- name: Demo on functions/filters
  hosts: local
  connection: local
  tasks:
  - name: Print the default variable 
    ansible.builtin.debug:
      msg: "Hello {{ course | default ('Ansible') }}" #If undefined variable then default can call the variable = Handling undefined variables
  - name: convert to uppercase
    vars: 
      greeting: "Hello Ramana"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"
  - name: convert to uppercase
    vars: 
      greeting: "Hello Ramana"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"
  - name: convert to uppercase
    vars: 
      numbers: [ 1,2,3,2,54,5,2,4,2 ]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

