- name: Command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
      # shell moule: its login to the server and execute command inside server : shell module
      # just issue the command: command module
  - name: check the process
    ansible.builtin.shell: ps -ef | grep ssh 
    register: output 
